

#define FightObjectsSingleObjectSingleInstanceIntelligenceAbilitiesIdentifier					0
#define FightObjectsSingleObjectSingleInstanceIntelligenceAccumulatedDamageIdentifier		1
#define FightObjectsSingleObjectSingleInstanceIntelligenceForcesToAccelerationIdentifier		2
#define FightObjectsSingleObjectSingleInstanceIntelligenceMovementPlayerIdentifier			3
#define FightObjectsSingleObjectSingleInstanceIntelligencePlayerGetInputIdentifier				4
#define FightObjectsSingleObjectSingleInstanceIntelligenceStairWayToHeavenIdentifier		5
#define FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineIdentifier		6
#define FightObjectsSingleObjectSingleInstanceIntelligenceHitLogicEnemyIdentifier				7
#define FightObjectsSingleObjectSingleInstanceIntelligenceHitLogicPlayerIdentifier				8
#define FightObjectsSingleObjectSingleInstanceIntelligenceFunctionAmount						9
void (*FightObjectsSingleObjectSingleInstanceIntelligenceFunction[FightObjectsSingleObjectSingleInstanceIntelligenceFunctionAmount])(FightObjectsSingleObjectSingleInstanceIntelligenceFunctionArguments) = {
FightObjectsSingleObjectSingleInstanceIntelligenceAbilities, 
FightObjectsSingleObjectSingleInstanceIntelligenceAccumulatedDamage, 
FightObjectsSingleObjectSingleInstanceIntelligenceForcesToAcceleration, 
FightObjectsSingleObjectSingleInstanceIntelligenceMovementPlayer, 
FightObjectsSingleObjectSingleInstanceIntelligencePlayerGetInput, 
FightObjectsSingleObjectSingleInstanceIntelligenceStairWayToHeaven, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachine, 
FightObjectsSingleObjectSingleInstanceIntelligenceHitLogicEnemy, 
FightObjectsSingleObjectSingleInstanceIntelligenceHitLogicPlayer
};
