FightObjectInstanceIntelligenceStruct FightObjectInstanceFluxDataIntelligenceCreatePlayerGetInput(){
return(FightObjectInstanceFluxDataIntelligenceCreateDataLess(FightObjectsSingleObjectSingleInstanceIntelligencePlayerGetInputIdentifier));
}