FightObjectInstanceIntelligenceStruct FightObjectInstanceFluxDataIntelligenceCreateAbilities(){
return(FightObjectInstanceFluxDataIntelligenceCreateDataLess(FightObjectsSingleObjectSingleInstanceIntelligenceAbilitiesIdentifier));
}