FightObjectInstanceIntelligenceStruct FightObjectInstanceFluxDataIntelligenceCreateEnemyStateMachine(){
FightObjectInstanceIntelligenceStruct ReturnData;

ReturnData = FightObjectInstanceFluxDataIntelligenceCreateDataLess(FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineIdentifier);
ReturnData.Buffer = FightObjectInstanceFluxDataIntelligenceCreateEnemyStateMachineBuffer();

return(ReturnData);
}