#define FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineWalkingSpeedMaximumLeft		-3
#define FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineWalkingSpeedMaximumRight		3
#define FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineWalkingSpeedMaximumUp		-3
#define FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineWalkingSpeedMaximumDown		3

void FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeStateFunctionDispatch(FightStruct* FightData, uint8 WhichObject, uint8 WhichInstance, FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineStruct* StateMachineData, uint8 FunctionIdentifier){

if(FunctionIdentifier == FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDeathAnimation){
FightObjectChangeAnimationSimplest(FightData->ObjectData[WhichObject].Instance[WhichInstance], EnemyDeathAnimation);
}
else if(FunctionIdentifier == FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineStartWalking){
StateMachineData->LogicData.SpeedX = RandomNumberInteger(FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineWalkingSpeedMaximumLeft, FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineWalkingSpeedMaximumRight);
StateMachineData->LogicData.SpeedZ = RandomNumberInteger(FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineWalkingSpeedMaximumUp, FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineWalkingSpeedMaximumDown);
}
else if(FunctionIdentifier == FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineAttackMeleeAnimation){
FightObjectChangeAnimationSimplest(FightData->ObjectData[WhichObject].Instance[WhichInstance], EnemyAttackMeleeAnimation);
}
else if(FunctionIdentifier == FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineAttackMeleeDeLoad){
StateMachineData->LogicData.EnemiesHitAlready = NULL;
}

}

void FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeState(
FightStruct* FightData, uint8 WhichObject, uint8 WhichInstance, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineStruct* StateMachineData, uint8 NewState, uint8 ExitFunction, uint8 TransitionFunction, uint8 EntryFunction
){

FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeStateFunctionDispatch(FightData, WhichObject, WhichInstance, StateMachineData, ExitFunction);
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeStateFunctionDispatch(FightData, WhichObject, WhichInstance, StateMachineData, TransitionFunction);
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeStateFunctionDispatch(FightData, WhichObject, WhichInstance, StateMachineData, EntryFunction);

StateMachineData->LogicData.CurrentState = NewState;

}