FightObjectInstanceIntelligenceStruct FightObjectInstanceFluxDataIntelligenceCreateStairWayToHeaven(){
return(FightObjectInstanceFluxDataIntelligenceCreateDataLess(FightObjectsSingleObjectSingleInstanceIntelligenceStairWayToHeavenIdentifier));
}