FightObjectInstanceIntelligenceStruct FightObjectInstanceFluxDataIntelligenceCreateAccumulatedDamage(){
return(FightObjectInstanceFluxDataIntelligenceCreateDataLess(FightObjectsSingleObjectSingleInstanceIntelligenceAccumulatedDamageIdentifier));
}