FightObjectInstanceIntelligenceStruct FightObjectInstanceFluxDataIntelligenceCreateForcesToAcceleration(){
return(FightObjectInstanceFluxDataIntelligenceCreateDataLess(FightObjectsSingleObjectSingleInstanceIntelligenceForcesToAccelerationIdentifier));
}