FightObjectInstanceIntelligenceStruct FightObjectInstanceFluxDataIntelligenceCreateMovementPlayer(){
return(FightObjectInstanceFluxDataIntelligenceCreateDataLess(FightObjectsSingleObjectSingleInstanceIntelligenceMovementPlayerIdentifier));
}