#define FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineStandingIdentifier			0
#define FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineWalkingIdentifier			1
#define FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineAttackMeleeIdentifier		2
#define FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineAttackRangeIdentifier		3
#define FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineHitIdentifier				4
#define FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDeathIdentifier				5



#define FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineStandingToWalkingTimeInSeconds	0.5f
#define FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineWalkingToStandingTimeInSeconds	0.5f

#define FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineProbabilityMaximum	100
#define FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineStandingToWalkingProbability		0.1f
#define FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineWalkingToStandingProbability		0.1f

void FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachine(FightStruct* FightData, uint8 WhichObject, uint8 WhichInstance, uint8 WhichIntelligence){

FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineStruct* StateMachineData;

StateMachineData = (FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineStruct*)FightData->ObjectData[WhichObject].Instance[WhichInstance].Intelligence[WhichIntelligence].Buffer;

if(StateMachineData->LogicData.CurrentState == FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineStandingIdentifier){
if(FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDead(FightData, WhichObject, WhichInstance)){
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeState(
FightData, WhichObject, WhichInstance, StateMachineData, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDeathIdentifier, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDeathAnimation
);
}
else if(FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineHit(FightData, WhichObject, WhichInstance)){
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeState(
FightData, WhichObject, WhichInstance, StateMachineData, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineHitIdentifier, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing 
);
}
else if(FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachinePlayerIsInAttackMeleeRange(FightData, WhichObject, WhichInstance)){
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeState(
FightData, WhichObject, WhichInstance, StateMachineData, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineAttackMeleeIdentifier, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineAttackMeleeAnimation 
);
}
else if(FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachinePlayerIsInAttackRangeRange(FightData, WhichObject, WhichInstance)){
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeState(FightData, WhichObject, WhichInstance, StateMachineData, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineAttackRangeIdentifier, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing 
);
}
else if(
StateMachineData->LogicData.Ticks > (FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineStandingToWalkingTimeInSeconds*FrameRate) &&
RandomNumberInteger(MinimumByteValue, FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineProbabilityMaximum) < (FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineStandingToWalkingProbability*FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineProbabilityMaximum)
){
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeState(FightData, WhichObject, WhichInstance, StateMachineData, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineWalkingIdentifier, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineStartWalking 
);
}
else{
if(FightData->ObjectData[WhichObject].Instance[WhichInstance].Loadable->CurrentAnimation != EnemyIdleAnimation){
FightObjectChangeAnimationSimplest(FightData->ObjectData[WhichObject].Instance[WhichInstance], EnemyIdleAnimation);
}
}
}


else if(StateMachineData->LogicData.CurrentState == FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineWalkingIdentifier){
if(FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDead(FightData, WhichObject, WhichInstance)){
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeState(FightData, WhichObject, WhichInstance, StateMachineData, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDeathIdentifier, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDeathAnimation
);
}
else if(FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineHit(FightData, WhichObject, WhichInstance)){
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeState(FightData, WhichObject, WhichInstance, StateMachineData, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineHitIdentifier, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing 
);
}
else if(FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachinePlayerIsInAttackMeleeRange(FightData, WhichObject, WhichInstance)){
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeState(FightData, WhichObject, WhichInstance, StateMachineData, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineAttackMeleeIdentifier, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineAttackMeleeAnimation 
);
}
else if(FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachinePlayerIsInAttackRangeRange(FightData, WhichObject, WhichInstance)){
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeState(FightData, WhichObject, WhichInstance, StateMachineData, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineAttackRangeIdentifier, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing 
);
}
else if(
StateMachineData->LogicData.Ticks > (FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineWalkingToStandingTimeInSeconds*FrameRate) &&
RandomNumberInteger(MinimumByteValue, FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineProbabilityMaximum) < (FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineWalkingToStandingProbability*FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineProbabilityMaximum)
){
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeState(FightData, WhichObject, WhichInstance, StateMachineData, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineStandingIdentifier, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing 
);
}
else{
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineWalkWithBias(FightData, WhichObject, WhichInstance, StateMachineData);
}
} 



else if(StateMachineData->LogicData.CurrentState == FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineAttackMeleeIdentifier){
if(FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDead(FightData, WhichObject, WhichInstance)){
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeState(FightData, WhichObject, WhichInstance, StateMachineData, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDeathIdentifier, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineAttackMeleeDeLoad, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDeathAnimation
);
}
else if(FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineHit(FightData, WhichObject, WhichInstance)){
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeState(FightData, WhichObject, WhichInstance, StateMachineData, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineHitIdentifier, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineAttackMeleeDeLoad, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing 
);
}
else if(FightData->ObjectData[WhichObject].Instance[WhichInstance].Loadable->CurrentAnimation != EnemyAttackMeleeAnimation){
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeState(FightData, WhichObject, WhichInstance, StateMachineData, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineStandingIdentifier,
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineAttackMeleeDeLoad, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing 
);
}
else{
FightCollisionCheckEnemyToPlayerRectangle2D(
FightData, FightCollisionCheckEnemyDependent, 
WhichObject, WhichInstance, 
StateMachineData->FluxData.MeleeOffsetData[0], 
&StateMachineData->Loadable.FightAttackData, &StateMachineData->LogicData.EnemiesHitAlready
);
}
}



else if(StateMachineData->LogicData.CurrentState == FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineAttackRangeIdentifier){
//?
}



else if(StateMachineData->LogicData.CurrentState == FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineHitIdentifier){
if(!FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineHit(FightData, WhichObject, WhichInstance)){
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineChangeState(FightData, WhichObject, WhichInstance, StateMachineData, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineStandingIdentifier,
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing, 
FightObjectsSingleObjectSingleInstanceIntelligenceEnemyStateMachineDoNothing 
);
}
else if(FightData->ObjectData[WhichObject].Instance[WhichInstance].Loadable->CurrentAnimation != StandardEnemyHitAnimation){
FightObjectChangeAnimationSimplest(FightData->ObjectData[WhichObject].Instance[WhichInstance], StandardEnemyHitAnimation);
}
}



else{
//Everlasting peace.
}


StateMachineData->LogicData.Ticks++;
}